title: Rensu Theart's blog
description: Curiousity driven code journeys
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
repository: rensutheart/rensutheart.github.io
github: [metadata]

encoding: UTF-8
kramdown:
  input: GFM
  hard_wrap: false
future: true
jailed: false
gfm_quirks: paragraph_end